// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    History: typeof import('./components/view/History.vue')['default']
    NewEpisode: typeof import('./components/view/NewEpisode.vue')['default']
    Progress: typeof import('./components/Progress.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./components/Section.vue')['default']
    SectionItem: typeof import('./components/view/SectionItem.vue')['default']
    VideoPlaye: typeof import('./components/VideoPlaye.vue')['default']
  }
}
